export const CUSTOMER_INFO_FETCH    =  "CUSTOMER_INFO_FETCH"
export const CUSTOMER_INFO_SUCCESS  =  "CUSTOMER_INFO_SUCCESS"
export const CUSTOMER_INFO_FAILED   =  "CUSTOMER_INFO_FAILED"

export const GET_ACCESS_TOKEN = "GET_ACCESS_TOKEN"